---
# tasks file for DEPLOY-IIS-FRAMEWORK

---
- name: .NET CORE APPLICATION IIS SERVER DEPLOYMENT
  hosts: "{{ IIS_SERVER }}"
  gather_facts: no
  tasks:

    - name: Creating website folder on IIS
      ansible.windows.win_file:
        path: "{{ WEB_PATH }}"
        state: directory

    - name: Create a new application pool in 'Started' state
      community.windows.win_iis_webapppool:
        name: "{{ POOL_NAME }}"
        state: started

    - name: Crate IIS site and stop for update
      community.windows.win_iis_website:
        name: "{{ WEB_NAME }}"
        state: stopped
        port: "{{ WEB_PORT }}"
        ip: "{{ WEB_IP }}"
        hostname: "{{ WEB_HOSTNAME }}"
        application_pool: "{{ POOL_NAME }}"
        physical_path: "{{ WEB_PATH }}"

    - name: Pull the repo to local IIS
      win_git:
        repo: "{{ CI_REPOSITORY_URL }}"
        dest: "{{ SRC_APP_PATH }}"
        branch: master
        update: no
        recursive: yes
        replace_dest: no
        accept_hostkey: yes

    - name: Place Publish Profile for IIS deployment
      win_template:
        src: templates/pubxml.j2
        dest: "{{ SRC_APP_PATH }}\\iisdeploy.pubxml"

    - name: Execute Nuget and download packages from packages.config file
      ansible.windows.win_command: nuget restore
      args:
        chdir: "{{ SRC_APP_PATH }}"

    - name: Execute MsBuild and publish to destination WEB_PATH for IIS
      ansible.windows.win_command: msbuild  /p:DeployOnBuild=true /p:PublishProfile={{ SRC_APP_PATH }}\\iisdeploy.pubxml
      args:
        chdir: "{{ SRC_APP_PATH }}"

    - name: Start IIS site
      community.windows.win_iis_website:
        name: "{{ WEB_NAME }}"
        state: started
      register: website

    - name: IIS Pool Info
      debug:
        var: website

...
