---
- name: Creating website folder on IIS
  ansible.windows.win_file:
    path: "{{ WEB_PATH }}"
    state: directory
    
- name: Create a new application pool in 'Started' state
  community.windows.win_iis_webapppool:
    name: "{{ POOL_NAME }}"
    state: started

- name: Crate IIS site and stop for update
  community.windows.win_iis_website:
    name: "{{ WEB_NAME }}"
    state: stopped
    port: "{{ WEB_PORT }}"
    ip: "{{ WEB_IP }}"
    hostname: "{{ WEB_HOSTNAME }}"
    application_pool: "{{ POOL_NAME }}"
    physical_path: "{{ WEB_PATH }}"

- name: Pull the repo to local IIS
  ignore_errors: yes
  win_git:
    repo: "{{ CI_REPOSITORY_URL }}"
    dest: "{{ GIT_DESTINATION }}"
    branch: "{{ CI_COMMIT_BRANCH }}"
    update: yes 
    recursive: yes
    replace_dest: yes
    accept_hostkey: yes

- name: Place Publish Profile for IIS deployment
  win_template:
    src: pubxml.j2
    dest: "{{ GIT_DESTINATION }}\\iisdeploy.pubxml"

- name: Execute Nuget and download packages from packages.config file
  ansible.windows.win_command: nuget restore
  args:
    chdir: "{{ GIT_DESTINATION }}"

- name: Execute MsBuild and publish to destination WEB_PATH for IIS
  ansible.windows.win_shell: cmd /c "msbuild  /p:DeployOnBuild=true /p:Configuration={{ BUILD_CONFIG }} /p:PublishProfile={{ GIT_DESTINATION }}\\iisdeploy.pubxml"
  args:
    chdir: "{{ GIT_DESTINATION }}"
  notify: 
    - Start IIS site

- name: IIS Pool Info
  debug:
    var: website
...
