---
# defaults file for DNS-MANAGER

ansible_user: "{{ lookup('community.hashi_vault.hashi_vault', 'secret=dns/dns_manager:username token=s.O6kDO74PBM4eiEm6TClmf9gX url=http://10.10.15.57:8200') }}"
ansible_ssh_pass: "{{ lookup('community.hashi_vault.hashi_vault', 'secret=dns/dns_manager:password token=s.O6kDO74PBM4eiEm6TClmf9gX url=http://10.10.15.57:8200') }}"
ansible_become_password: "{{ ansible_ssh_pass }}"

URL: "{{ lookup('env','URL') }}"
WEBSERVER: "{{ lookup('env','WEBSERVER') }}"
...
