---
# tasks file for DNS-MANAGER

- name: DNS MANAGER
  become: yes
  command: grep {{ URL }} -s /etc/hosts 1>test1.txt 2>test2.txt || sh -c  "echo '{{ NGINX_SERVER }}  {{ URL }}' >> /etc/hosts"
  ignore_errors: true
  notify:
    - Reload dnsmasq
...
