---
# tasks file for DNS-MANAGER

- name: DNS MANAGER
  become: yes
  command: grep {{ URL }} /etc/hosts || sh -c  "echo '{{ NGINX_SERVER }}  {{ URL }}' >> /etc/hosts"
  notify:
    - Reload dnsmasq
...
